# Generated by Django 2.1.3 on 2018-11-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffnumber', models.CharField(blank=True, max_length=300, null=True)),
                ('staffname', models.CharField(blank=True, max_length=300, null=True)),
                ('staffnamePinyin', models.CharField(blank=True, max_length=300, null=True)),
                ('staffnamePinyinab', models.CharField(blank=True, max_length=300, null=True)),
                ('staffdept', models.TextField(blank=True, null=True)),
                ('staffunit', models.TextField(blank=True, null=True)),
                ('staffsex', models.TextField(blank=True, null=True)),
                ('staffphone', models.CharField(blank=True, max_length=300, null=True)),
                ('staffemail', models.CharField(blank=True, max_length=300, null=True)),
                ('staffoaccount', models.CharField(blank=True, max_length=300, null=True)),
                ('staffidcard', models.CharField(blank=True, max_length=300, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('isfail', models.CharField(blank=True, max_length=2, null=True)),
                ('failtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
