# Generated by Django 2.1.3 on 2018-11-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deptment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptmentnumber', models.CharField(blank=True, max_length=300, null=True)),
                ('sdeptmentname', models.CharField(blank=True, max_length=300, null=True)),
                ('deptmentnamePinyin', models.CharField(blank=True, max_length=300, null=True)),
                ('sdeptmentnamePinyinab', models.CharField(blank=True, max_length=300, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('isfail', models.CharField(blank=True, max_length=2, null=True)),
                ('failtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staffdeptclass',
            field=models.TextField(blank=True, null=True),
        ),
    ]
