# Generated by Django 2.1.3 on 2018-11-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181123_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staffnamePinyin',
            new_name='staffnamepinyin',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staffnamePinyinab',
            new_name='staffnamepinyinab',
        ),
    ]
