# Generated by Django 2.1.3 on 2018-11-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181124_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='sport_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportnumber', models.CharField(blank=True, max_length=300, null=True)),
                ('requestnumber', models.CharField(blank=True, max_length=300, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('isfail', models.CharField(blank=True, max_length=2, null=True)),
                ('failtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
