# Generated by Django 2.1.3 on 2018-11-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sport_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport_staff_request',
            old_name='ssport_staff_request_info',
            new_name='sport_staff_request_info',
        ),
    ]
