# Generated by Django 2.1.3 on 2018-11-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181124_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requestlist',
        ),
    ]
