# Generated by Django 2.1.3 on 2018-11-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181124_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='userVisitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_visit_ip', models.CharField(blank=True, max_length=300, null=True)),
                ('user_visit_cookies', models.TextField(blank=True, null=True)),
                ('user_visit_terminal_type', models.TextField(blank=True, null=True)),
                ('user_visit_form', models.TextField(blank=True, null=True)),
                ('user_visit_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('isfail', models.CharField(blank=True, max_length=2, null=True)),
                ('failtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
