# Generated by Django 2.1.3 on 2018-11-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_staffinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='staffworkplace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
