# Generated by Django 2.1.3 on 2018-11-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_staffinfo_staffworkplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportlist',
            name='sportenddate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sportlist',
            name='sportstartdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
