# Generated by Django 2.1.3 on 2018-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181128_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportlist',
            name='sportauthor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
