# Generated by Django 2.1.3 on 2018-11-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_staffinfo_bz'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='bztime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
