# Generated by Django 2.1.3 on 2018-12-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_emailverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailsports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='邮箱')),
                ('emailsporttitle', models.CharField(max_length=100, null=True, verbose_name='邮件活动题目')),
                ('emailsportcontent', models.TextField(blank=True, null=True, verbose_name='邮件活动内容')),
                ('emailsportlink', models.CharField(max_length=100, null=True, verbose_name='邮件活动链接')),
                ('create_date', models.DateField(auto_now_add=True, null=True, verbose_name='发送时间')),
                ('is_fail', models.CharField(default='0', max_length=10, null=True, verbose_name='是否失效：0 不失效、1 失效')),
            ],
        ),
    ]
