# Generated by Django 2.1.3 on 2018-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_emailsports'),
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamesnumber', models.CharField(blank=True, max_length=300, null=True, verbose_name='游戏id')),
                ('gamesname', models.CharField(blank=True, max_length=300, null=True, verbose_name='游戏名字')),
                ('gamesinfo', models.TextField(blank=True, null=True, verbose_name='游戏简介')),
                ('gamestype', models.CharField(blank=True, max_length=300, null=True, verbose_name='游戏类别')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('isfail', models.CharField(blank=True, max_length=2, null=True)),
                ('failtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gamesinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamesnumber', models.CharField(blank=True, max_length=300, null=True, verbose_name='游戏id')),
                ('gamesquestion', models.TextField(blank=True, null=True, verbose_name='游戏问题')),
                ('gamesanswer', models.CharField(blank=True, max_length=300, null=True, verbose_name='游戏答案')),
                ('gamesstatus', models.CharField(blank=True, max_length=300, null=True, verbose_name='游戏状态：-1，0，1，2...')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('isfail', models.CharField(blank=True, max_length=2, null=True)),
                ('failtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
